name: Sync draft spec with ballerina.io

on:
  push:
    tags:    
      - '*'
jobs:
  sync_draft_spec:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.WEBSITE_TOKEN }}

    steps:       
      - name: Checkout ballerina-spec
        uses: actions/checkout@v2

      - name: Clone ballerina-dev-website
        run: git clone https://shafreenAnfar:$GITHUB_TOKEN@github.com/ballerina-platform/ballerina-dev-website.git

      - name: Make a new folder location
        run: |
          cd ballerina-dev-website/spec/draft
          array=($(echo $GITHUB_REF | tr "/" "\n"))
          len=${#array[@]}
          echo "${array[len-1]}"
          mkdir "${array[len-1]}"
          pwd
          echo "::set-env name=NEW_FOLDER::${array[len-1]}"

      - name: Update the latest to new url
        run: |
          cd ballerina-dev-website/spec/draft/latest
          echo -e "---\nredirect_to: /spec/draft/$NEW_FOLDER/\n---" > index.md

      - name: Install xsltproc
        run: sudo apt-get install -y xsltproc

      - name: Make
        run: |
          git checkout $GITHUB_REF -b tmp
          cd lang
          make all
          cp -r build/lib/ ../ballerina-dev-website/spec/draft/$NEW_FOLDER
          cp -r build/style/ ../ballerina-dev-website/spec/draft/$NEW_FOLDER
          cp -r build/spec.html ../ballerina-dev-website/spec/draft/$NEW_FOLDER/index.html

      - name: Update the list of draft specs
        run: python3 .github/scripts/append.py ballerina-dev-website/_data/draft_spec.json $NEW_FOLDER

      - name: Sync ballerina-spec with ballerina dev site
        run: |
          cd ballerina-dev-website
          git checkout automate-spec-sync-$GITHUB_SHA 2>/dev/null || git checkout -b automate-spec-sync-$GITHUB_SHA
          git pull origin master

          git config --global user.email "ballerina-bot@ballerina.org"
          git config --global user.name "shafreenAnfar"

          git add ballerina-dev-website/_data/draft_spec.json
          git add spec/draft/
          git commit --allow-empty -m 'Create new draft spec'
          
          git push --set-upstream origin automate-spec-sync-$GITHUB_SHA
          echo 'Successfully pushed to automate-spec-sync-$GITHUB_SHA branch'

      - name: Create pull request for spec-sync
        shell: bash
        run: |
          cd ballerina-dev-website
          curl -fsSL https://github.com/github/hub/raw/master/script/get | bash -s 2.14.1
          bin/hub pull-request -m "[Automated] Sync new spec-tag with ballerina dev site"
        env:
          GITHUB_TOKEN: ${{ secrets.WEBSITE_TOKEN }}
