name: Sync draft spec with ballerina.io

on: push

jobs:
  sync_live_spec:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.BAL_BOT_PAT }}

    steps:       
      - name: Checkout ballerina-spec
        uses: actions/checkout@v2

      - name: Clone ballerina-dev-website
        run: git clone https://ballerina-bot:$GITHUB_TOKEN@github.com/ballerina-platform/ballerina-dev-website.git

      - name: Install xsltproc
        run: sudo apt-get install -y xsltproc

      - name: Make
        run: |
          cd lang
          make all

      - name: Sync ballerina live spec with ballerina dev site
        run: |
          cd ballerina-dev-website
          git pull origin master

          git config --global user.email "ballerina-bot@ballerina.org"
          git config --global user.name "ballerina-bot"

          git rm -r spec/lang/live/
          cp -r ../lang/build/ spec/lang/live/
          git add spec/lang/live/
          git commit --allow-empty -m "[Automated] Update live spec"
          
      - name: Commit new changes
        shell: bash
        run: |
          cd ballerina-dev-website
          curl -fsSL https://github.com/github/hub/raw/master/script/get | bash -s 2.14.1
          bin/hub push
        env:
          GITHUB_TOKEN: ${{ secrets.BAL_BOT_PAT }}
