name: Snapshot Build

on:
  push:
    branches:    
      - abc  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Make
      run: |
        sudo apt-get install -y xsltproc
        cd lang
        make all
    - name: GitHub Pages
      if: success()
      continue-on-error: true
      uses: crazy-max/ghaction-github-pages@v1.2.5
      with:
        # Git branch where assets will be deployed
        target_branch: gh-pages
        # Create incremental commit instead of doing push force
        keep_history: true
        allow_empty_commit: false
        # Build directory to deploy
        build_dir: lang/build
      env:
        # This will not trigger Github pages, See https://github.com/peaceiris/actions-gh-pages/issues/9 Fixed it temparally
        # By using https://htmlpreview.github.io/
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
